zeta:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  BL_1_controller:
    type: effort_controllers/JointPositionController
    joint: BL_1
    pid: {p: 1.0, i: 1.0, d: 0.0}

  BL_2_controller:
    type: effort_controllers/JointPositionController
    joint: BL_2
    pid: {p: 1.0, i: 1.0, d: 0.0}

  BL_3_controller:
    type: effort_controllers/JointPositionController
    joint: BL_3
    pid: { p: 1.0, i: 1.0, d: 0.0 }

  FL_1_controller:
    type: effort_controllers/JointPositionController
    joint: FL_1
    pid: { p: 1.0, i: 1.0, d: 0.0 }

  FL_2_controller:
    type: effort_controllers/JointPositionController
    joint: FL_2
    pid: { p: 1.0, i: 1.0, d: 0.0 }

  FL_3_controller:
    type: effort_controllers/JointPositionController
    joint: FL_3
    pid: { p: 1.0, i: 1.0, d: 0.0 }

  FR_1_controller:
    type: effort_controllers/JointPositionController
    joint: FR_1
    pid: { p: 1.0, i: 1.0, d: 0.0 }

  FR_2_controller:
    type: effort_controllers/JointPositionController
    joint: FR_2
    pid: { p: 1.0, i: 1.0, d: 0.0 }

  FR_3_controller:
    type: effort_controllers/JointPositionController
    joint: FR_3
    pid: { p: 1.0, i: 1.0, d: 0.0 }

  BR_1_controller:
    type: effort_controllers/JointPositionController
    joint: BR_1
    pid: { p: 1.0, i: 1.0, d: 0.0 }

  BR_2_controller:
    type: effort_controllers/JointPositionController
    joint: BR_2
    pid: { p: 1.0, i: 1.0, d: 0.0 }

  BR_3_controller:
    type: effort_controllers/JointPositionController
    joint: BR_3
    pid: { p: 1.0, i: 1.0, d: 0.0 }


