zeta:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  BL_3_controller:
    type: effort_controllers/JointPositionController
    joint: BL_3
    pid: {p: 1.0, i: 1.0, d: 0.0}